// Generated by packages/icons/generate.mjs. Do not edit directly.
package com.nook.app.share.ui

import androidx.compose.foundation.Canvas
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.drawscope.Stroke

enum class NookIconName {
    Icon16ArrowDiagonal,
    Icon16ArrowDown,
    Icon16ArrowRight,
    Icon16Chat,
    Icon16Clock,
    Icon16Group,
    Icon16Info,
    Icon16Insta,
    Icon16Location,
    Icon16Paper,
    Icon16Pen,
    Icon16User,
    Icon16Version,
    Icon24Add,
    Icon24Back,
    Icon24Delete,
    Icon24Group,
    Icon24Share,
    Icon32Edit,
    Icon32GroupSelected,
    Icon32GroupUnselected,
    Icon32MapSelected,
    Icon32MapUnselected,
    Icon32StarOff,
    Icon32StarOn,
    Icon40Location,
    CheckBtnSelected,
    CheckBtnUnselected,
    LocationCrosshair,
}

@Composable
fun NookIcon(name: NookIconName, modifier: Modifier = Modifier) {
    Canvas(modifier) {
        val viewBox = when (name) {
            NookIconName.Icon16ArrowDiagonal -> 16f to 16f
            NookIconName.Icon16ArrowDown -> 16f to 16f
            NookIconName.Icon16ArrowRight -> 16f to 16f
            NookIconName.Icon16Chat -> 16f to 16f
            NookIconName.Icon16Clock -> 16f to 16f
            NookIconName.Icon16Group -> 16f to 16f
            NookIconName.Icon16Info -> 16f to 16f
            NookIconName.Icon16Insta -> 16f to 16f
            NookIconName.Icon16Location -> 16f to 16f
            NookIconName.Icon16Paper -> 16f to 16f
            NookIconName.Icon16Pen -> 16f to 16f
            NookIconName.Icon16User -> 16f to 16f
            NookIconName.Icon16Version -> 16f to 16f
            NookIconName.Icon24Add -> 24f to 24f
            NookIconName.Icon24Back -> 24f to 24f
            NookIconName.Icon24Delete -> 24f to 24f
            NookIconName.Icon24Group -> 24f to 24f
            NookIconName.Icon24Share -> 24f to 24f
            NookIconName.Icon32Edit -> 32f to 32f
            NookIconName.Icon32GroupSelected -> 32f to 32f
            NookIconName.Icon32GroupUnselected -> 32f to 32f
            NookIconName.Icon32MapSelected -> 32f to 32f
            NookIconName.Icon32MapUnselected -> 32f to 32f
            NookIconName.Icon32StarOff -> 32f to 32f
            NookIconName.Icon32StarOn -> 32f to 32f
            NookIconName.Icon40Location -> 40f to 40f
            NookIconName.CheckBtnSelected -> 24f to 24f
            NookIconName.CheckBtnUnselected -> 24f to 24f
            NookIconName.LocationCrosshair -> 17f to 17f
        }
        drawContext.canvas.save()
        drawContext.canvas.scale(size.width / viewBox.first, size.height / viewBox.second, Offset.Zero)
        when (name) {
        NookIconName.Icon16ArrowDiagonal -> {
            val path0 = Path().apply {

                moveTo(3f, 13f)
                lineTo(13f, 3f)
                moveTo(13f, 10.7273f)
                lineTo(13f, 3f)
                lineTo(5.27273f, 3f)
            }
            drawPath(path = path0, color = Color(0xFF848B96), style = Stroke(width = 1f, cap = StrokeCap.Butt))
        }
        NookIconName.Icon16ArrowDown -> {
            val path0 = Path().apply {

                moveTo(2.66699f, 5.33301f)
                lineTo(8.00033f, 10.6663f)
                lineTo(13.3337f, 5.33301f)
            }
            drawPath(path = path0, color = Color(0xFF1F1F1F), style = Stroke(width = 1f, cap = StrokeCap.Butt))
        }
        NookIconName.Icon16ArrowRight -> {
            val path0 = Path().apply {

                moveTo(5.33398f, 13.334f)
                lineTo(10.6673f, 8.00065f)
                lineTo(5.33398f, 2.66732f)
            }
            drawPath(path = path0, color = Color(0xFF1F1F1F), style = Stroke(width = 1f, cap = StrokeCap.Butt))
        }
        NookIconName.Icon16Chat -> {
            val path0 = Path().apply {

                moveTo(7.99967f, 1.33301f)
                cubicTo(11.6817f, 1.33301f, 14.6663f, 4.31767f, 14.6663f, 7.99967f)
                cubicTo(14.6663f, 11.6817f, 11.6817f, 14.6663f, 7.99967f, 14.6663f)
                lineTo(2.66634f, 14.6663f)
                cubicTo(2.31272f, 14.6663f, 1.97358f, 14.5259f, 1.72353f, 14.2758f)
                cubicTo(1.47348f, 14.0258f, 1.33301f, 13.6866f, 1.33301f, 13.333f)
                lineTo(1.33301f, 7.99967f)
                cubicTo(1.33301f, 4.31767f, 4.31767f, 1.33301f, 7.99967f, 1.33301f)
                close()
                moveTo(7.99967f, 9.33301f)
                lineTo(5.99967f, 9.33301f)
                cubicTo(5.82286f, 9.33301f, 5.65329f, 9.40325f, 5.52827f, 9.52827f)
                cubicTo(5.40325f, 9.65329f, 5.33301f, 9.82286f, 5.33301f, 9.99967f)
                cubicTo(5.33301f, 10.1765f, 5.40325f, 10.3461f, 5.52827f, 10.4711f)
                cubicTo(5.65329f, 10.5961f, 5.82286f, 10.6663f, 5.99967f, 10.6663f)
                lineTo(7.99967f, 10.6663f)
                cubicTo(8.17649f, 10.6663f, 8.34606f, 10.5961f, 8.47108f, 10.4711f)
                cubicTo(8.5961f, 10.3461f, 8.66634f, 10.1765f, 8.66634f, 9.99967f)
                cubicTo(8.66634f, 9.82286f, 8.5961f, 9.65329f, 8.47108f, 9.52827f)
                cubicTo(8.34606f, 9.40325f, 8.17649f, 9.33301f, 7.99967f, 9.33301f)
                close()
                moveTo(9.99967f, 6.66634f)
                lineTo(5.99967f, 6.66634f)
                cubicTo(5.82975f, 6.66653f, 5.66632f, 6.73159f, 5.54276f, 6.84824f)
                cubicTo(5.4192f, 6.96489f, 5.34485f, 7.12431f, 5.33489f, 7.29394f)
                cubicTo(5.32493f, 7.46357f, 5.38012f, 7.63059f, 5.48918f, 7.7609f)
                cubicTo(5.59824f, 7.8912f, 5.75294f, 7.97494f, 5.92167f, 7.99501f)
                lineTo(5.99967f, 7.99967f)
                lineTo(9.99967f, 7.99967f)
                cubicTo(10.1696f, 7.99949f, 10.333f, 7.93442f, 10.4566f, 7.81778f)
                cubicTo(10.5801f, 7.70113f, 10.6545f, 7.54171f, 10.6645f, 7.37208f)
                cubicTo(10.6744f, 7.20245f, 10.6192f, 7.03542f, 10.5102f, 6.90512f)
                cubicTo(10.4011f, 6.77482f, 10.2464f, 6.69108f, 10.0777f, 6.67101f)
                lineTo(9.99967f, 6.66634f)
                close()
            }
            drawPath(path = path0, color = Color(0xFF848B96))
        }
        NookIconName.Icon16Clock -> {
            val path0 = Path().apply {
                fillType = PathFillType.EvenOdd

                moveTo(2f, 8f)
                cubicTo(2f, 6.4087f, 2.63214f, 4.88258f, 3.75736f, 3.75736f)
                cubicTo(4.88258f, 2.63214f, 6.4087f, 2f, 8f, 2f)
                cubicTo(9.5913f, 2f, 11.1174f, 2.63214f, 12.2426f, 3.75736f)
                cubicTo(13.3679f, 4.88258f, 14f, 6.4087f, 14f, 8f)
                cubicTo(14f, 9.5913f, 13.3679f, 11.1174f, 12.2426f, 12.2426f)
                cubicTo(11.1174f, 13.3679f, 9.5913f, 14f, 8f, 14f)
                cubicTo(6.4087f, 14f, 4.88258f, 13.3679f, 3.75736f, 12.2426f)
                cubicTo(2.63214f, 11.1174f, 2f, 9.5913f, 2f, 8f)
                close()
                moveTo(8.64286f, 4.35714f)
                cubicTo(8.64286f, 4.18665f, 8.57513f, 4.02313f, 8.45457f, 3.90257f)
                cubicTo(8.33401f, 3.78202f, 8.1705f, 3.71429f, 8f, 3.71429f)
                cubicTo(7.8295f, 3.71429f, 7.66599f, 3.78202f, 7.54543f, 3.90257f)
                cubicTo(7.42487f, 4.02313f, 7.35714f, 4.18665f, 7.35714f, 4.35714f)
                lineTo(7.35714f, 8f)
                cubicTo(7.35714f, 8.35486f, 7.64514f, 8.64286f, 8f, 8.64286f)
                lineTo(10.7857f, 8.64286f)
                cubicTo(10.9562f, 8.64286f, 11.1197f, 8.57513f, 11.2403f, 8.45457f)
                cubicTo(11.3608f, 8.33401f, 11.4286f, 8.1705f, 11.4286f, 8f)
                cubicTo(11.4286f, 7.8295f, 11.3608f, 7.66599f, 11.2403f, 7.54543f)
                cubicTo(11.1197f, 7.42487f, 10.9562f, 7.35714f, 10.7857f, 7.35714f)
                lineTo(8.64286f, 7.35714f)
                lineTo(8.64286f, 4.35714f)
                close()
            }
            drawPath(path = path0, color = Color(0xFFB5BBC3))
        }
        NookIconName.Icon16Group -> {
            val path0 = Path().apply {

                moveTo(3.5f, 2f)
                cubicTo(3.10218f, 2f, 2.72064f, 2.15804f, 2.43934f, 2.43934f)
                cubicTo(2.15804f, 2.72064f, 2f, 3.10218f, 2f, 3.5f)
                lineTo(2f, 5.5f)
                cubicTo(2f, 5.89782f, 2.15804f, 6.27936f, 2.43934f, 6.56066f)
                cubicTo(2.72064f, 6.84196f, 3.10218f, 7f, 3.5f, 7f)
                lineTo(5.5f, 7f)
                cubicTo(5.89782f, 7f, 6.27936f, 6.84196f, 6.56066f, 6.56066f)
                cubicTo(6.84196f, 6.27936f, 7f, 5.89782f, 7f, 5.5f)
                lineTo(7f, 3.5f)
                cubicTo(7f, 3.10218f, 6.84196f, 2.72064f, 6.56066f, 2.43934f)
                cubicTo(6.27936f, 2.15804f, 5.89782f, 2f, 5.5f, 2f)
                lineTo(3.5f, 2f)
                close()
                moveTo(3.5f, 9f)
                cubicTo(3.10218f, 9f, 2.72064f, 9.15804f, 2.43934f, 9.43934f)
                cubicTo(2.15804f, 9.72064f, 2f, 10.1022f, 2f, 10.5f)
                lineTo(2f, 12.5f)
                cubicTo(2f, 12.8978f, 2.15804f, 13.2794f, 2.43934f, 13.5607f)
                cubicTo(2.72064f, 13.842f, 3.10218f, 14f, 3.5f, 14f)
                lineTo(5.5f, 14f)
                cubicTo(5.89782f, 14f, 6.27936f, 13.842f, 6.56066f, 13.5607f)
                cubicTo(6.84196f, 13.2794f, 7f, 12.8978f, 7f, 12.5f)
                lineTo(7f, 10.5f)
                cubicTo(7f, 10.1022f, 6.84196f, 9.72064f, 6.56066f, 9.43934f)
                cubicTo(6.27936f, 9.15804f, 5.89782f, 9f, 5.5f, 9f)
                lineTo(3.5f, 9f)
                close()
                moveTo(9f, 3.5f)
                cubicTo(9f, 3.10218f, 9.15804f, 2.72064f, 9.43934f, 2.43934f)
                cubicTo(9.72064f, 2.15804f, 10.1022f, 2f, 10.5f, 2f)
                lineTo(12.5f, 2f)
                cubicTo(12.8978f, 2f, 13.2794f, 2.15804f, 13.5607f, 2.43934f)
                cubicTo(13.842f, 2.72064f, 14f, 3.10218f, 14f, 3.5f)
                lineTo(14f, 5.5f)
                cubicTo(14f, 5.89782f, 13.842f, 6.27936f, 13.5607f, 6.56066f)
                cubicTo(13.2794f, 6.84196f, 12.8978f, 7f, 12.5f, 7f)
                lineTo(10.5f, 7f)
                cubicTo(10.1022f, 7f, 9.72064f, 6.84196f, 9.43934f, 6.56066f)
                cubicTo(9.15804f, 6.27936f, 9f, 5.89782f, 9f, 5.5f)
                lineTo(9f, 3.5f)
                close()
                moveTo(10.5f, 9f)
                cubicTo(10.1022f, 9f, 9.72064f, 9.15804f, 9.43934f, 9.43934f)
                cubicTo(9.15804f, 9.72064f, 9f, 10.1022f, 9f, 10.5f)
                lineTo(9f, 12.5f)
                cubicTo(9f, 12.8978f, 9.15804f, 13.2794f, 9.43934f, 13.5607f)
                cubicTo(9.72064f, 13.842f, 10.1022f, 14f, 10.5f, 14f)
                lineTo(12.5f, 14f)
                cubicTo(12.8978f, 14f, 13.2794f, 13.842f, 13.5607f, 13.5607f)
                cubicTo(13.842f, 13.2794f, 14f, 12.8978f, 14f, 12.5f)
                lineTo(14f, 10.5f)
                cubicTo(14f, 10.1022f, 13.842f, 9.72064f, 13.5607f, 9.43934f)
                cubicTo(13.2794f, 9.15804f, 12.8978f, 9f, 12.5f, 9f)
                lineTo(10.5f, 9f)
                close()
            }
            drawPath(path = path0, color = Color(0xFFB5BBC3))
        }
        NookIconName.Icon16Info -> {
            val path0 = Path().apply {

                moveTo(7.99967f, 1.33301f)
                cubicTo(11.6817f, 1.33301f, 14.6663f, 4.31767f, 14.6663f, 7.99967f)
                cubicTo(14.6663f, 11.6817f, 11.6817f, 14.6663f, 7.99967f, 14.6663f)
                cubicTo(4.31767f, 14.6663f, 1.33301f, 11.6817f, 1.33301f, 7.99967f)
                cubicTo(1.33301f, 4.31767f, 4.31767f, 1.33301f, 7.99967f, 1.33301f)
                close()
                moveTo(7.99301f, 6.66634f)
                lineTo(7.33301f, 6.66634f)
                cubicTo(7.16309f, 6.66653f, 6.99965f, 6.73159f, 6.8761f, 6.84824f)
                cubicTo(6.75254f, 6.96489f, 6.67818f, 7.12431f, 6.66823f, 7.29394f)
                cubicTo(6.65827f, 7.46357f, 6.71346f, 7.63059f, 6.82252f, 7.7609f)
                cubicTo(6.93158f, 7.8912f, 7.08628f, 7.97494f, 7.25501f, 7.99501f)
                lineTo(7.33301f, 7.99967f)
                lineTo(7.33301f, 11.3263f)
                cubicTo(7.33301f, 11.673f, 7.59567f, 11.9597f, 7.93301f, 11.9957f)
                lineTo(8.00634f, 11.9997f)
                lineTo(8.33301f, 11.9997f)
                cubicTo(8.47322f, 11.9997f, 8.60986f, 11.9555f, 8.7235f, 11.8734f)
                cubicTo(8.83714f, 11.7912f, 8.922f, 11.6754f, 8.966f, 11.5422f)
                cubicTo(9.01001f, 11.4091f, 9.01092f, 11.2655f, 8.96861f, 11.1318f)
                cubicTo(8.9263f, 10.9982f, 8.84293f, 10.8812f, 8.73034f, 10.7977f)
                lineTo(8.66634f, 10.7557f)
                lineTo(8.66634f, 7.33967f)
                cubicTo(8.66634f, 6.99301f, 8.40368f, 6.70634f, 8.06634f, 6.67034f)
                lineTo(7.99301f, 6.66634f)
                close()
                moveTo(7.99967f, 4.66634f)
                cubicTo(7.82286f, 4.66634f, 7.65329f, 4.73658f, 7.52827f, 4.8616f)
                cubicTo(7.40325f, 4.98663f, 7.33301f, 5.1562f, 7.33301f, 5.33301f)
                cubicTo(7.33301f, 5.50982f, 7.40325f, 5.67939f, 7.52827f, 5.80441f)
                cubicTo(7.65329f, 5.92944f, 7.82286f, 5.99967f, 7.99967f, 5.99967f)
                cubicTo(8.17649f, 5.99967f, 8.34606f, 5.92944f, 8.47108f, 5.80441f)
                cubicTo(8.5961f, 5.67939f, 8.66634f, 5.50982f, 8.66634f, 5.33301f)
                cubicTo(8.66634f, 5.1562f, 8.5961f, 4.98663f, 8.47108f, 4.8616f)
                cubicTo(8.34606f, 4.73658f, 8.17649f, 4.66634f, 7.99967f, 4.66634f)
                close()
            }
            drawPath(path = path0, color = Color(0xFF848B96))
        }
        NookIconName.Icon16Insta -> {
            val path0 = Path().apply {

                moveTo(10.6667f, 2f)
                cubicTo(11.5507f, 2f, 12.3986f, 2.35119f, 13.0237f, 2.97631f)
                cubicTo(13.6488f, 3.60143f, 14f, 4.44928f, 14f, 5.33333f)
                lineTo(14f, 10.6667f)
                cubicTo(14f, 11.5507f, 13.6488f, 12.3986f, 13.0237f, 13.0237f)
                cubicTo(12.3986f, 13.6488f, 11.5507f, 14f, 10.6667f, 14f)
                lineTo(5.33333f, 14f)
                cubicTo(4.44928f, 14f, 3.60143f, 13.6488f, 2.97631f, 13.0237f)
                cubicTo(2.35119f, 12.3986f, 2f, 11.5507f, 2f, 10.6667f)
                lineTo(2f, 5.33333f)
                cubicTo(2f, 4.44928f, 2.35119f, 3.60143f, 2.97631f, 2.97631f)
                cubicTo(3.60143f, 2.35119f, 4.44928f, 2f, 5.33333f, 2f)
                lineTo(10.6667f, 2f)
                close()
                moveTo(8f, 5.33333f)
                cubicTo(7.29276f, 5.33333f, 6.61448f, 5.61428f, 6.11438f, 6.11438f)
                cubicTo(5.61428f, 6.61448f, 5.33333f, 7.29276f, 5.33333f, 8f)
                cubicTo(5.33333f, 8.70724f, 5.61428f, 9.38552f, 6.11438f, 9.88562f)
                cubicTo(6.61448f, 10.3857f, 7.29276f, 10.6667f, 8f, 10.6667f)
                cubicTo(8.70724f, 10.6667f, 9.38552f, 10.3857f, 9.88562f, 9.88562f)
                cubicTo(10.3857f, 9.38552f, 10.6667f, 8.70724f, 10.6667f, 8f)
                cubicTo(10.6667f, 7.29276f, 10.3857f, 6.61448f, 9.88562f, 6.11438f)
                cubicTo(9.38552f, 5.61428f, 8.70724f, 5.33333f, 8f, 5.33333f)
                close()
                moveTo(8f, 6.66667f)
                cubicTo(8.35362f, 6.66667f, 8.69276f, 6.80714f, 8.94281f, 7.05719f)
                cubicTo(9.19286f, 7.30724f, 9.33333f, 7.64638f, 9.33333f, 8f)
                cubicTo(9.33333f, 8.35362f, 9.19286f, 8.69276f, 8.94281f, 8.94281f)
                cubicTo(8.69276f, 9.19286f, 8.35362f, 9.33333f, 8f, 9.33333f)
                cubicTo(7.64638f, 9.33333f, 7.30724f, 9.19286f, 7.05719f, 8.94281f)
                cubicTo(6.80714f, 8.69276f, 6.66667f, 8.35362f, 6.66667f, 8f)
                cubicTo(6.66667f, 7.64638f, 6.80714f, 7.30724f, 7.05719f, 7.05719f)
                cubicTo(7.30724f, 6.80714f, 7.64638f, 6.66667f, 8f, 6.66667f)
                close()
                moveTo(11f, 4.33333f)
                cubicTo(10.8232f, 4.33333f, 10.6536f, 4.40357f, 10.5286f, 4.5286f)
                cubicTo(10.4036f, 4.65362f, 10.3333f, 4.82319f, 10.3333f, 5f)
                cubicTo(10.3333f, 5.17681f, 10.4036f, 5.34638f, 10.5286f, 5.4714f)
                cubicTo(10.6536f, 5.59643f, 10.8232f, 5.66667f, 11f, 5.66667f)
                cubicTo(11.1768f, 5.66667f, 11.3464f, 5.59643f, 11.4714f, 5.4714f)
                cubicTo(11.5964f, 5.34638f, 11.6667f, 5.17681f, 11.6667f, 5f)
                cubicTo(11.6667f, 4.82319f, 11.5964f, 4.65362f, 11.4714f, 4.5286f)
                cubicTo(11.3464f, 4.40357f, 11.1768f, 4.33333f, 11f, 4.33333f)
                close()
            }
            drawPath(path = path0, color = Color(0xFFFFFFFF))
        }
        NookIconName.Icon16Location -> {
            val path0 = Path().apply {

                moveTo(8f, 1.33301f)
                cubicTo(9.5913f, 1.33301f, 11.1174f, 1.96515f, 12.2426f, 3.09037f)
                cubicTo(13.3679f, 4.21559f, 14f, 5.74171f, 14f, 7.33301f)
                cubicTo(14f, 9.38234f, 12.8827f, 11.0597f, 11.7053f, 12.263f)
                cubicTo(11.117f, 12.8576f, 10.4752f, 13.3968f, 9.788f, 13.8737f)
                lineTo(9.504f, 14.067f)
                lineTo(9.37067f, 14.1557f)
                lineTo(9.11933f, 14.3157f)
                lineTo(8.89533f, 14.4523f)
                lineTo(8.618f, 14.6137f)
                cubicTo(8.42967f, 14.7209f, 8.2167f, 14.7772f, 8f, 14.7772f)
                cubicTo(7.7833f, 14.7772f, 7.57033f, 14.7209f, 7.382f, 14.6137f)
                lineTo(7.10467f, 14.4523f)
                lineTo(6.758f, 14.239f)
                lineTo(6.63f, 14.1557f)
                lineTo(6.35667f, 13.9737f)
                cubicTo(5.61532f, 13.4719f, 4.92471f, 12.899f, 4.29467f, 12.263f)
                cubicTo(3.11733f, 11.059f, 2f, 9.38234f, 2f, 7.33301f)
                cubicTo(2f, 5.74171f, 2.63214f, 4.21559f, 3.75736f, 3.09037f)
                cubicTo(4.88258f, 1.96515f, 6.4087f, 1.33301f, 8f, 1.33301f)
                close()
                moveTo(8f, 5.33301f)
                cubicTo(7.73736f, 5.33301f, 7.47728f, 5.38474f, 7.23463f, 5.48525f)
                cubicTo(6.99198f, 5.58576f, 6.7715f, 5.73308f, 6.58579f, 5.91879f)
                cubicTo(6.40007f, 6.10451f, 6.25275f, 6.32499f, 6.15224f, 6.56764f)
                cubicTo(6.05173f, 6.81029f, 6f, 7.07036f, 6f, 7.33301f)
                cubicTo(6f, 7.59565f, 6.05173f, 7.85572f, 6.15224f, 8.09837f)
                cubicTo(6.25275f, 8.34103f, 6.40007f, 8.5615f, 6.58579f, 8.74722f)
                cubicTo(6.7715f, 8.93294f, 6.99198f, 9.08026f, 7.23463f, 9.18077f)
                cubicTo(7.47728f, 9.28128f, 7.73736f, 9.33301f, 8f, 9.33301f)
                cubicTo(8.53043f, 9.33301f, 9.03914f, 9.12229f, 9.41421f, 8.74722f)
                cubicTo(9.78929f, 8.37215f, 10f, 7.86344f, 10f, 7.33301f)
                cubicTo(10f, 6.80258f, 9.78929f, 6.29387f, 9.41421f, 5.91879f)
                cubicTo(9.03914f, 5.54372f, 8.53043f, 5.33301f, 8f, 5.33301f)
                close()
            }
            drawPath(path = path0, color = Color(0xFFB5BBC3))
        }
        NookIconName.Icon16Paper -> {
            val path0 = Path().apply {

                moveTo(10.6667f, 2f)
                cubicTo(11.0031f, 1.99989f, 11.327f, 2.12694f, 11.5737f, 2.35566f)
                cubicTo(11.8204f, 2.58439f, 11.9714f, 2.8979f, 11.9967f, 3.23333f)
                lineTo(12f, 3.33333f)
                lineTo(12f, 6.66667f)
                lineTo(13f, 6.66667f)
                cubicTo(13.2486f, 6.66668f, 13.4883f, 6.75928f, 13.6723f, 6.92641f)
                cubicTo(13.8563f, 7.09355f, 13.9715f, 7.32323f, 13.9953f, 7.57067f)
                lineTo(14f, 7.66667f)
                lineTo(14f, 12.6667f)
                cubicTo(14f, 13.1768f, 13.8051f, 13.6677f, 13.4551f, 14.0388f)
                cubicTo(13.1052f, 14.41f, 12.6266f, 14.6334f, 12.1173f, 14.6633f)
                lineTo(12f, 14.6667f)
                lineTo(3.33333f, 14.6667f)
                cubicTo(2.99695f, 14.6668f, 2.67296f, 14.5397f, 2.4263f, 14.311f)
                cubicTo(2.17965f, 14.0823f, 2.02856f, 13.7688f, 2.00333f, 13.4333f)
                lineTo(2f, 13.3333f)
                lineTo(2f, 3.33333f)
                cubicTo(1.99989f, 2.99695f, 2.12694f, 2.67296f, 2.35566f, 2.4263f)
                cubicTo(2.58439f, 2.17965f, 2.8979f, 2.02856f, 3.23333f, 2.00333f)
                lineTo(3.33333f, 2f)
                lineTo(10.6667f, 2f)
                close()
                moveTo(12.6667f, 8f)
                lineTo(12f, 8f)
                lineTo(12f, 13.3333f)
                cubicTo(12.1768f, 13.3333f, 12.3464f, 13.2631f, 12.4714f, 13.1381f)
                cubicTo(12.5964f, 13.013f, 12.6667f, 12.8435f, 12.6667f, 12.6667f)
                lineTo(12.6667f, 8f)
                close()
                moveTo(7.33333f, 8.66667f)
                lineTo(5.33333f, 8.66667f)
                cubicTo(5.16341f, 8.66686f, 4.99998f, 8.73192f, 4.87642f, 8.84857f)
                cubicTo(4.75286f, 8.96521f, 4.67851f, 9.12464f, 4.66855f, 9.29426f)
                cubicTo(4.65859f, 9.46389f, 4.71378f, 9.63092f, 4.82284f, 9.76122f)
                cubicTo(4.9319f, 9.89152f, 5.0866f, 9.97526f, 5.25533f, 9.99533f)
                lineTo(5.33333f, 10f)
                lineTo(7.33333f, 10f)
                cubicTo(7.50325f, 9.99981f, 7.66669f, 9.93475f, 7.79025f, 9.8181f)
                cubicTo(7.9138f, 9.70146f, 7.98816f, 9.54203f, 7.99812f, 9.3724f)
                cubicTo(8.00807f, 9.20278f, 7.95288f, 9.03575f, 7.84382f, 8.90545f)
                cubicTo(7.73476f, 8.77514f, 7.58006f, 8.6914f, 7.41133f, 8.67133f)
                lineTo(7.33333f, 8.66667f)
                close()
                moveTo(8.66667f, 5.33333f)
                lineTo(5.33333f, 5.33333f)
                cubicTo(5.15652f, 5.33333f, 4.98695f, 5.40357f, 4.86193f, 5.5286f)
                cubicTo(4.7369f, 5.65362f, 4.66667f, 5.82319f, 4.66667f, 6f)
                cubicTo(4.66667f, 6.17681f, 4.7369f, 6.34638f, 4.86193f, 6.4714f)
                cubicTo(4.98695f, 6.59643f, 5.15652f, 6.66667f, 5.33333f, 6.66667f)
                lineTo(8.66667f, 6.66667f)
                cubicTo(8.84348f, 6.66667f, 9.01305f, 6.59643f, 9.13807f, 6.4714f)
                cubicTo(9.2631f, 6.34638f, 9.33333f, 6.17681f, 9.33333f, 6f)
                cubicTo(9.33333f, 5.82319f, 9.2631f, 5.65362f, 9.13807f, 5.5286f)
                cubicTo(9.01305f, 5.40357f, 8.84348f, 5.33333f, 8.66667f, 5.33333f)
                close()
            }
            drawPath(path = path0, color = Color(0xFF848B96))
        }
        NookIconName.Icon16Pen -> {
            val path0 = Path().apply {
                fillType = PathFillType.EvenOdd

                moveTo(13.4207f, 2.10706f)
                cubicTo(13.0456f, 1.73212f, 12.537f, 1.52148f, 12.0067f, 1.52148f)
                cubicTo(11.4764f, 1.52148f, 10.9677f, 1.73212f, 10.5927f, 2.10706f)
                lineTo(10.1214f, 2.57906f)
                lineTo(13.4214f, 5.87906f)
                lineTo(13.892f, 5.40772f)
                cubicTo(14.0778f, 5.222f, 14.2251f, 5.00151f, 14.3256f, 4.75884f)
                cubicTo(14.4262f, 4.51616f, 14.4779f, 4.25606f, 14.4779f, 3.99339f)
                cubicTo(14.4779f, 3.73072f, 14.4262f, 3.47062f, 14.3256f, 3.22795f)
                cubicTo(14.2251f, 2.98527f, 14.0778f, 2.76478f, 13.892f, 2.57906f)
                lineTo(13.4207f, 2.10706f)
                close()
                moveTo(12.478f, 6.82172f)
                lineTo(9.17802f, 3.52172f)
                lineTo(3.11802f, 9.58239f)
                cubicTo(2.98541f, 9.71503f, 2.89277f, 9.88228f, 2.85068f, 10.0651f)
                lineTo(2.16468f, 13.0351f)
                cubicTo(2.13912f, 13.1453f, 2.14206f, 13.2603f, 2.1732f, 13.3691f)
                cubicTo(2.20435f, 13.4779f, 2.26269f, 13.577f, 2.34272f, 13.657f)
                cubicTo(2.42276f, 13.7371f, 2.52185f, 13.7954f, 2.63066f, 13.8265f)
                cubicTo(2.73947f, 13.8577f, 2.85442f, 13.8606f, 2.96468f, 13.8351f)
                lineTo(5.93535f, 13.1497f)
                cubicTo(6.11789f, 13.1075f, 6.2849f, 13.0149f, 6.41735f, 12.8824f)
                lineTo(12.478f, 6.82172f)
                close()
            }
            drawPath(path = path0, color = Color(0xFFB5BBC3))
        }
        NookIconName.Icon16User -> {
            val path0 = Path().apply {

                moveTo(10.6667f, 9.33301f)
                cubicTo(11.5256f, 9.33306f, 12.3514f, 9.6647f, 12.9719f, 10.2588f)
                cubicTo(13.5923f, 10.8529f, 13.9594f, 11.6635f, 13.9967f, 12.5217f)
                lineTo(14f, 12.6663f)
                lineTo(14f, 13.333f)
                cubicTo(14.0001f, 13.6694f, 13.8731f, 13.9934f, 13.6443f, 14.24f)
                cubicTo(13.4156f, 14.4867f, 13.1021f, 14.6378f, 12.7667f, 14.663f)
                lineTo(12.6667f, 14.6663f)
                lineTo(3.33333f, 14.6663f)
                cubicTo(2.99695f, 14.6664f, 2.67296f, 14.5394f, 2.4263f, 14.3107f)
                cubicTo(2.17965f, 14.082f, 2.02856f, 13.7684f, 2.00333f, 13.433f)
                lineTo(2f, 13.333f)
                lineTo(2f, 12.6663f)
                cubicTo(2.00005f, 11.8074f, 2.33169f, 10.9816f, 2.92577f, 10.3612f)
                cubicTo(3.51985f, 9.74075f, 4.3305f, 9.37362f, 5.18867f, 9.33634f)
                lineTo(5.33333f, 9.33301f)
                lineTo(10.6667f, 9.33301f)
                close()
                moveTo(8f, 1.33301f)
                cubicTo(8.88406f, 1.33301f, 9.7319f, 1.6842f, 10.357f, 2.30932f)
                cubicTo(10.9821f, 2.93444f, 11.3333f, 3.78229f, 11.3333f, 4.66634f)
                cubicTo(11.3333f, 5.5504f, 10.9821f, 6.39824f, 10.357f, 7.02336f)
                cubicTo(9.7319f, 7.64849f, 8.88406f, 7.99967f, 8f, 7.99967f)
                cubicTo(7.11595f, 7.99967f, 6.2681f, 7.64849f, 5.64298f, 7.02336f)
                cubicTo(5.01786f, 6.39824f, 4.66667f, 5.5504f, 4.66667f, 4.66634f)
                cubicTo(4.66667f, 3.78229f, 5.01786f, 2.93444f, 5.64298f, 2.30932f)
                cubicTo(6.2681f, 1.6842f, 7.11595f, 1.33301f, 8f, 1.33301f)
                close()
            }
            drawPath(path = path0, color = Color(0xFF848B96))
        }
        NookIconName.Icon16Version -> {
            val path0 = Path().apply {

                moveTo(13.497f, 9.83301f)
                cubicTo(14.1203f, 10.2423f, 14.0916f, 11.191f, 13.411f, 11.5503f)
                lineTo(8.62364f, 14.081f)
                cubicTo(8.43157f, 14.1826f, 8.21758f, 14.2357f, 8.00031f, 14.2357f)
                cubicTo(7.78303f, 14.2357f, 7.56905f, 14.1826f, 7.37697f, 14.081f)
                lineTo(2.58964f, 11.5503f)
                cubicTo(1.90964f, 11.1903f, 1.88031f, 10.2423f, 2.50364f, 9.83301f)
                lineTo(2.54564f, 9.85968f)
                lineTo(7.37697f, 12.4143f)
                cubicTo(7.56905f, 12.5159f, 7.78303f, 12.569f, 8.00031f, 12.569f)
                cubicTo(8.21758f, 12.569f, 8.43157f, 12.5159f, 8.62364f, 12.4143f)
                lineTo(13.411f, 9.88368f)
                cubicTo(13.4406f, 9.86817f, 13.4689f, 9.85126f, 13.497f, 9.83301f)
                close()
                moveTo(13.497f, 7.16635f)
                cubicTo(13.6346f, 7.25754f, 13.7476f, 7.3814f, 13.8257f, 7.52687f)
                cubicTo(13.9038f, 7.67234f, 13.9447f, 7.83489f, 13.9447f, 8.00001f)
                cubicTo(13.9447f, 8.16514f, 13.9038f, 8.32769f, 13.8257f, 8.47316f)
                cubicTo(13.7476f, 8.61863f, 13.6346f, 8.74249f, 13.497f, 8.83368f)
                lineTo(13.411f, 8.88368f)
                lineTo(8.62364f, 11.4143f)
                cubicTo(8.44952f, 11.5064f, 8.25717f, 11.5588f, 8.0604f, 11.5677f)
                cubicTo(7.86363f, 11.5765f, 7.66734f, 11.5417f, 7.48564f, 11.4657f)
                lineTo(7.37764f, 11.4143f)
                lineTo(2.58964f, 8.88368f)
                cubicTo(1.90964f, 8.52368f, 1.88031f, 7.57568f, 2.50364f, 7.16635f)
                lineTo(2.54564f, 7.19302f)
                lineTo(7.37697f, 9.74768f)
                cubicTo(7.55118f, 9.83986f, 7.74365f, 9.89228f, 7.94055f, 9.90116f)
                cubicTo(8.13744f, 9.91003f, 8.33385f, 9.87515f, 8.51564f, 9.79902f)
                lineTo(8.62364f, 9.74768f)
                lineTo(13.411f, 7.21701f)
                cubicTo(13.4406f, 7.2015f, 13.4689f, 7.1846f, 13.497f, 7.16635f)
                close()
                moveTo(8.62364f, 1.91835f)
                lineTo(13.411f, 4.44901f)
                cubicTo(14.1216f, 4.82435f, 14.1216f, 5.84235f, 13.411f, 6.21701f)
                lineTo(8.62364f, 8.74835f)
                cubicTo(8.43157f, 8.84993f, 8.21758f, 8.90302f, 8.00031f, 8.90302f)
                cubicTo(7.78303f, 8.90302f, 7.56905f, 8.84993f, 7.37697f, 8.74835f)
                lineTo(2.58964f, 6.21701f)
                cubicTo(1.87897f, 5.84168f, 1.87897f, 4.82435f, 2.58964f, 4.44901f)
                lineTo(7.37697f, 1.91835f)
                cubicTo(7.56905f, 1.81677f, 7.78303f, 1.76367f, 8.00031f, 1.76367f)
                cubicTo(8.21758f, 1.76367f, 8.43157f, 1.81677f, 8.62364f, 1.91835f)
                close()
            }
            drawPath(path = path0, color = Color(0xFF848B96))
        }
        NookIconName.Icon24Add -> {
            val path0 = Path().apply {

                moveTo(24f, 12f)
                cubicTo(24f, 18.6274f, 18.6274f, 24f, 12f, 24f)
                cubicTo(5.37258f, 24f, 0f, 18.6274f, 0f, 12f)
                cubicTo(0f, 5.37258f, 5.37258f, 0f, 12f, 0f)
                cubicTo(18.6274f, 0f, 24f, 5.37258f, 24f, 12f)
                close()
            }
            drawPath(path = path0, color = Color(0xFFF4F5F7))
            val path1 = Path().apply {

                moveTo(8f, 11.9941f)
                lineTo(16f, 11.9941f)
            }
            drawPath(path = path1, color = Color(0xFF99A0AC), style = Stroke(width = 1.5f, cap = StrokeCap.Square))
            val path2 = Path().apply {

                moveTo(12.0029f, 7.99805f)
                lineTo(12.0029f, 15.998f)
            }
            drawPath(path = path2, color = Color(0xFF99A0AC), style = Stroke(width = 1.5f, cap = StrokeCap.Square))
        }
        NookIconName.Icon24Back -> {
            val path0 = Path().apply {

                moveTo(12.0001f, 4f)
                lineTo(4f, 11.9999f)
                lineTo(12.0001f, 20f)
            }
            drawPath(path = path0, color = Color(0xFF848B96), style = Stroke(width = 1.5f, cap = StrokeCap.Butt))
        }
        NookIconName.Icon24Delete -> {
            drawCircle(color = Color(0xFFE4E6E9), center = Offset(12f, 12f), radius = 12f)
            val path1 = Path().apply {

                moveTo(9f, 8.99805f)
                lineTo(15f, 14.998f)
            }
            drawPath(path = path1, color = Color(0xFF848B96), style = Stroke(width = 1.5f, cap = StrokeCap.Square))
            val path2 = Path().apply {

                moveTo(15f, 8.99805f)
                lineTo(9f, 14.998f)
            }
            drawPath(path = path2, color = Color(0xFF848B96), style = Stroke(width = 1.5f, cap = StrokeCap.Square))
        }
        NookIconName.Icon24Group -> {
            val path0 = Path().apply {
                fillType = PathFillType.EvenOdd

                moveTo(3f, 6f)
                cubicTo(3f, 5.20435f, 3.31607f, 4.44129f, 3.87868f, 3.87868f)
                cubicTo(4.44129f, 3.31607f, 5.20435f, 3f, 6f, 3f)
                lineTo(8.25f, 3f)
                cubicTo(9.04565f, 3f, 9.80871f, 3.31607f, 10.3713f, 3.87868f)
                cubicTo(10.9339f, 4.44129f, 11.25f, 5.20435f, 11.25f, 6f)
                lineTo(11.25f, 8.25f)
                cubicTo(11.25f, 9.04565f, 10.9339f, 9.80871f, 10.3713f, 10.3713f)
                cubicTo(9.80871f, 10.9339f, 9.04565f, 11.25f, 8.25f, 11.25f)
                lineTo(6f, 11.25f)
                cubicTo(5.20435f, 11.25f, 4.44129f, 10.9339f, 3.87868f, 10.3713f)
                cubicTo(3.31607f, 9.80871f, 3f, 9.04565f, 3f, 8.25f)
                lineTo(3f, 6f)
                close()
                moveTo(12.75f, 6f)
                cubicTo(12.75f, 5.20435f, 13.0661f, 4.44129f, 13.6287f, 3.87868f)
                cubicTo(14.1913f, 3.31607f, 14.9544f, 3f, 15.75f, 3f)
                lineTo(18f, 3f)
                cubicTo(18.7956f, 3f, 19.5587f, 3.31607f, 20.1213f, 3.87868f)
                cubicTo(20.6839f, 4.44129f, 21f, 5.20435f, 21f, 6f)
                lineTo(21f, 8.25f)
                cubicTo(21f, 9.04565f, 20.6839f, 9.80871f, 20.1213f, 10.3713f)
                cubicTo(19.5587f, 10.9339f, 18.7956f, 11.25f, 18f, 11.25f)
                lineTo(15.75f, 11.25f)
                cubicTo(14.9544f, 11.25f, 14.1913f, 10.9339f, 13.6287f, 10.3713f)
                cubicTo(13.0661f, 9.80871f, 12.75f, 9.04565f, 12.75f, 8.25f)
                lineTo(12.75f, 6f)
                close()
                moveTo(3f, 15.75f)
                cubicTo(3f, 14.9544f, 3.31607f, 14.1913f, 3.87868f, 13.6287f)
                cubicTo(4.44129f, 13.0661f, 5.20435f, 12.75f, 6f, 12.75f)
                lineTo(8.25f, 12.75f)
                cubicTo(9.04565f, 12.75f, 9.80871f, 13.0661f, 10.3713f, 13.6287f)
                cubicTo(10.9339f, 14.1913f, 11.25f, 14.9544f, 11.25f, 15.75f)
                lineTo(11.25f, 18f)
                cubicTo(11.25f, 18.7956f, 10.9339f, 19.5587f, 10.3713f, 20.1213f)
                cubicTo(9.80871f, 20.6839f, 9.04565f, 21f, 8.25f, 21f)
                lineTo(6f, 21f)
                cubicTo(5.20435f, 21f, 4.44129f, 20.6839f, 3.87868f, 20.1213f)
                cubicTo(3.31607f, 19.5587f, 3f, 18.7956f, 3f, 18f)
                lineTo(3f, 15.75f)
                close()
                moveTo(12.75f, 15.75f)
                cubicTo(12.75f, 14.9544f, 13.0661f, 14.1913f, 13.6287f, 13.6287f)
                cubicTo(14.1913f, 13.0661f, 14.9544f, 12.75f, 15.75f, 12.75f)
                lineTo(18f, 12.75f)
                cubicTo(18.7956f, 12.75f, 19.5587f, 13.0661f, 20.1213f, 13.6287f)
                cubicTo(20.6839f, 14.1913f, 21f, 14.9544f, 21f, 15.75f)
                lineTo(21f, 18f)
                cubicTo(21f, 18.7956f, 20.6839f, 19.5587f, 20.1213f, 20.1213f)
                cubicTo(19.5587f, 20.6839f, 18.7956f, 21f, 18f, 21f)
                lineTo(15.75f, 21f)
                cubicTo(14.9544f, 21f, 14.1913f, 20.6839f, 13.6287f, 20.1213f)
                cubicTo(13.0661f, 19.5587f, 12.75f, 18.7956f, 12.75f, 18f)
                lineTo(12.75f, 15.75f)
                close()
            }
            drawPath(path = path0, color = Color(0xFF1F1F1F))
        }
        NookIconName.Icon24Share -> {
            drawCircle(color = Color(0xFF848B96), center = Offset(17.3028f, 5.77743f), radius = 2.69735f, style = Stroke(width = 1.5f, cap = StrokeCap.Butt))
            drawCircle(color = Color(0xFF848B96), center = Offset(17.3028f, 18.2169f), radius = 2.69735f, style = Stroke(width = 1.5f, cap = StrokeCap.Butt))
            drawCircle(color = Color(0xFF848B96), center = Offset(6.69735f, 12.0011f), radius = 2.69735f, style = Stroke(width = 1.5f, cap = StrokeCap.Butt))
            val path3 = Path().apply {

                moveTo(8.98438f, 10.5733f)
                cubicTo(11.3709f, 9.19726f, 12.9872f, 8.26535f, 14.965f, 7.125f)
                moveTo(8.98438f, 13.4284f)
                cubicTo(11.3719f, 14.8028f, 12.9885f, 15.7335f, 14.9674f, 16.8726f)
            }
            drawPath(path = path3, color = Color(0xFF848B96), style = Stroke(width = 1.5f, cap = StrokeCap.Butt))
        }
        NookIconName.Icon32Edit -> {
            drawCircle(color = Color(0xFFFFFFFF), center = Offset(16f, 16f), radius = 13.5f)
            drawCircle(color = Color(0xFFE4E6E9), center = Offset(16f, 16f), radius = 13.5f, style = Stroke(width = 1f, cap = StrokeCap.Butt))
            val path2 = Path().apply {

                moveTo(18.5973f, 11.1361f)
                cubicTo(18.6724f, 11.061f, 18.7943f, 11.061f, 18.8695f, 11.1361f)
                lineTo(20.8633f, 13.1299f)
                cubicTo(20.9385f, 13.2051f, 20.9385f, 13.327f, 20.8633f, 13.4022f)
                lineTo(19.7059f, 14.5596f)
                lineTo(17.4398f, 12.2936f)
                lineTo(18.5973f, 11.1361f)
                close()
            }
            drawPath(path = path2, color = Color(0xFF4E5662), style = Stroke(width = 1f, cap = StrokeCap.Butt))
            val path3 = Path().apply {

                moveTo(19.7062f, 14.5595f)
                lineTo(13.8415f, 20.4242f)
                cubicTo(13.8149f, 20.4508f, 13.7811f, 20.469f, 13.7443f, 20.4766f)
                lineTo(11.2315f, 20.9952f)
                cubicTo(11.0961f, 21.0231f, 10.9763f, 20.9031f, 11.004f, 20.7677f)
                lineTo(11.5226f, 18.2549f)
                cubicTo(11.5302f, 18.2181f, 11.5484f, 18.1843f, 11.575f, 18.1577f)
                lineTo(17.4407f, 12.293f)
                lineTo(19.7062f, 14.5595f)
                close()
            }
            drawPath(path = path3, color = Color(0xFF4E5662), style = Stroke(width = 1f, cap = StrokeCap.Butt))
        }
        NookIconName.Icon32GroupSelected -> {
            val path0 = Path().apply {

                moveTo(9.33301f, 17.3887f)
                lineTo(11.833f, 17.3887f)
                cubicTo(12.5697f, 17.3887f, 13.2769f, 17.6812f, 13.7979f, 18.2021f)
                cubicTo(14.3188f, 18.7231f, 14.6113f, 19.4303f, 14.6113f, 20.167f)
                lineTo(14.6113f, 22.667f)
                cubicTo(14.6112f, 23.4035f, 14.3186f, 24.11f, 13.7979f, 24.6309f)
                cubicTo(13.2769f, 25.1518f, 12.5697f, 25.4443f, 11.833f, 25.4443f)
                lineTo(9.33301f, 25.4443f)
                cubicTo(8.59641f, 25.4442f, 7.89f, 25.1517f, 7.36914f, 24.6309f)
                cubicTo(6.84828f, 24.11f, 6.55575f, 23.4036f, 6.55566f, 22.667f)
                lineTo(6.55566f, 20.167f)
                cubicTo(6.55566f, 19.4303f, 6.84821f, 18.7231f, 7.36914f, 18.2021f)
                cubicTo(7.88998f, 17.6814f, 8.59649f, 17.3888f, 9.33301f, 17.3887f)
                close()
                moveTo(20.167f, 17.3887f)
                lineTo(22.667f, 17.3887f)
                cubicTo(23.4035f, 17.3888f, 24.11f, 17.6814f, 24.6309f, 18.2021f)
                cubicTo(25.1518f, 18.7231f, 25.4443f, 19.4303f, 25.4443f, 20.167f)
                lineTo(25.4443f, 22.667f)
                cubicTo(25.4443f, 23.4036f, 25.1517f, 24.11f, 24.6309f, 24.6309f)
                cubicTo(24.11f, 25.1517f, 23.4036f, 25.4443f, 22.667f, 25.4443f)
                lineTo(20.167f, 25.4443f)
                cubicTo(19.4303f, 25.4443f, 18.7231f, 25.1518f, 18.2021f, 24.6309f)
                cubicTo(17.6814f, 24.11f, 17.3888f, 23.4035f, 17.3887f, 22.667f)
                lineTo(17.3887f, 20.167f)
                cubicTo(17.3887f, 19.4303f, 17.6812f, 18.7231f, 18.2021f, 18.2021f)
                cubicTo(18.7231f, 17.6812f, 19.4303f, 17.3887f, 20.167f, 17.3887f)
                close()
                moveTo(9.33301f, 6.55566f)
                lineTo(11.833f, 6.55566f)
                cubicTo(12.5697f, 6.55566f, 13.2769f, 6.84821f, 13.7979f, 7.36914f)
                cubicTo(14.3186f, 7.88998f, 14.6112f, 8.59649f, 14.6113f, 9.33301f)
                lineTo(14.6113f, 11.833f)
                cubicTo(14.6113f, 12.5697f, 14.3188f, 13.2769f, 13.7979f, 13.7979f)
                cubicTo(13.2769f, 14.3188f, 12.5697f, 14.6113f, 11.833f, 14.6113f)
                lineTo(9.33301f, 14.6113f)
                cubicTo(8.59649f, 14.6112f, 7.88998f, 14.3186f, 7.36914f, 13.7979f)
                cubicTo(6.84821f, 13.2769f, 6.55566f, 12.5697f, 6.55566f, 11.833f)
                lineTo(6.55566f, 9.33301f)
                cubicTo(6.55575f, 8.59641f, 6.84828f, 7.89f, 7.36914f, 7.36914f)
                cubicTo(7.89f, 6.84828f, 8.59641f, 6.55575f, 9.33301f, 6.55566f)
                close()
                moveTo(20.167f, 6.55566f)
                lineTo(22.667f, 6.55566f)
                cubicTo(23.4036f, 6.55575f, 24.11f, 6.84828f, 24.6309f, 7.36914f)
                cubicTo(25.1517f, 7.89f, 25.4442f, 8.59641f, 25.4443f, 9.33301f)
                lineTo(25.4443f, 11.833f)
                cubicTo(25.4443f, 12.5697f, 25.1518f, 13.2769f, 24.6309f, 13.7979f)
                cubicTo(24.11f, 14.3186f, 23.4035f, 14.6112f, 22.667f, 14.6113f)
                lineTo(20.167f, 14.6113f)
                cubicTo(19.4303f, 14.6113f, 18.7231f, 14.3188f, 18.2021f, 13.7979f)
                cubicTo(17.6812f, 13.2769f, 17.3887f, 12.5697f, 17.3887f, 11.833f)
                lineTo(17.3887f, 9.33301f)
                cubicTo(17.3888f, 8.59649f, 17.6814f, 7.88998f, 18.2021f, 7.36914f)
                cubicTo(18.7231f, 6.84821f, 19.4303f, 6.55566f, 20.167f, 6.55566f)
                close()
            }
            drawPath(path = path0, color = Color(0xFF1F1F1F))
            drawPath(path = path0, color = Color(0xFF1F1F1F), style = Stroke(width = 1.11111f, cap = StrokeCap.Butt))
        }
        NookIconName.Icon32GroupUnselected -> {
            val path0 = Path().apply {

                moveTo(13.5f, 20.1667f)
                cubicTo(13.5f, 19.7246f, 13.3243f, 19.3008f, 13.0117f, 18.9883f)
                cubicTo(12.6992f, 18.6757f, 12.2754f, 18.5f, 11.8333f, 18.5f)
                lineTo(9.33333f, 18.5f)
                cubicTo(8.89131f, 18.5f, 8.46751f, 18.6757f, 8.15495f, 18.9883f)
                cubicTo(7.84239f, 19.3008f, 7.66667f, 19.7246f, 7.66667f, 20.1667f)
                lineTo(7.66667f, 22.6667f)
                cubicTo(7.66667f, 23.1087f, 7.84239f, 23.5325f, 8.15495f, 23.8451f)
                cubicTo(8.46751f, 24.1576f, 8.89131f, 24.3333f, 9.33333f, 24.3333f)
                lineTo(11.8333f, 24.3333f)
                cubicTo(12.2754f, 24.3333f, 12.6992f, 24.1576f, 13.0117f, 23.8451f)
                cubicTo(13.3243f, 23.5325f, 13.5f, 23.1087f, 13.5f, 22.6667f)
                lineTo(13.5f, 20.1667f)
                close()
                moveTo(24.3333f, 20.1667f)
                cubicTo(24.3333f, 19.7246f, 24.1576f, 19.3008f, 23.8451f, 18.9883f)
                cubicTo(23.5325f, 18.6757f, 23.1087f, 18.5f, 22.6667f, 18.5f)
                lineTo(20.1667f, 18.5f)
                cubicTo(19.7246f, 18.5f, 19.3008f, 18.6757f, 18.9883f, 18.9883f)
                cubicTo(18.6757f, 19.3008f, 18.5f, 19.7246f, 18.5f, 20.1667f)
                lineTo(18.5f, 22.6667f)
                cubicTo(18.5f, 23.1087f, 18.6757f, 23.5325f, 18.9883f, 23.8451f)
                cubicTo(19.3008f, 24.1576f, 19.7246f, 24.3333f, 20.1667f, 24.3333f)
                lineTo(22.6667f, 24.3333f)
                cubicTo(23.1087f, 24.3333f, 23.5325f, 24.1576f, 23.8451f, 23.8451f)
                cubicTo(24.1576f, 23.5325f, 24.3333f, 23.1087f, 24.3333f, 22.6667f)
                lineTo(24.3333f, 20.1667f)
                close()
                moveTo(13.5f, 9.33333f)
                cubicTo(13.5f, 8.89131f, 13.3243f, 8.46751f, 13.0117f, 8.15495f)
                cubicTo(12.6992f, 7.84239f, 12.2754f, 7.66667f, 11.8333f, 7.66667f)
                lineTo(9.33333f, 7.66667f)
                cubicTo(8.89131f, 7.66667f, 8.46751f, 7.84239f, 8.15495f, 8.15495f)
                cubicTo(7.84239f, 8.46751f, 7.66667f, 8.89131f, 7.66667f, 9.33333f)
                lineTo(7.66667f, 11.8333f)
                cubicTo(7.66667f, 12.2754f, 7.84239f, 12.6992f, 8.15495f, 13.0117f)
                cubicTo(8.46751f, 13.3243f, 8.89131f, 13.5f, 9.33333f, 13.5f)
                lineTo(11.8333f, 13.5f)
                cubicTo(12.2754f, 13.5f, 12.6992f, 13.3243f, 13.0117f, 13.0117f)
                cubicTo(13.3243f, 12.6992f, 13.5f, 12.2754f, 13.5f, 11.8333f)
                lineTo(13.5f, 9.33333f)
                close()
                moveTo(24.3333f, 9.33333f)
                cubicTo(24.3333f, 8.89131f, 24.1576f, 8.46751f, 23.8451f, 8.15495f)
                cubicTo(23.5325f, 7.84239f, 23.1087f, 7.66667f, 22.6667f, 7.66667f)
                lineTo(20.1667f, 7.66667f)
                cubicTo(19.7246f, 7.66667f, 19.3008f, 7.84239f, 18.9883f, 8.15495f)
                cubicTo(18.6757f, 8.46751f, 18.5f, 8.89131f, 18.5f, 9.33333f)
                lineTo(18.5f, 11.8333f)
                cubicTo(18.5f, 12.2754f, 18.6757f, 12.6992f, 18.9883f, 13.0117f)
                cubicTo(19.3008f, 13.3243f, 19.7246f, 13.5f, 20.1667f, 13.5f)
                lineTo(22.6667f, 13.5f)
                cubicTo(23.1087f, 13.5f, 23.5325f, 13.3243f, 23.8451f, 13.0117f)
                cubicTo(24.1576f, 12.6992f, 24.3333f, 12.2754f, 24.3333f, 11.8333f)
                lineTo(24.3333f, 9.33333f)
                close()
                moveTo(15.1667f, 22.6667f)
                cubicTo(15.1667f, 23.5507f, 14.8152f, 24.3983f, 14.1901f, 25.0234f)
                cubicTo(13.565f, 25.6486f, 12.7174f, 26f, 11.8333f, 26f)
                lineTo(9.33333f, 26f)
                cubicTo(8.44928f, 26f, 7.60168f, 25.6486f, 6.97656f, 25.0234f)
                cubicTo(6.35144f, 24.3983f, 6f, 23.5507f, 6f, 22.6667f)
                lineTo(6f, 20.1667f)
                cubicTo(6f, 19.2826f, 6.35144f, 18.435f, 6.97656f, 17.8099f)
                cubicTo(7.60168f, 17.1848f, 8.44928f, 16.8333f, 9.33333f, 16.8333f)
                lineTo(11.8333f, 16.8333f)
                cubicTo(12.7174f, 16.8333f, 13.565f, 17.1848f, 14.1901f, 17.8099f)
                cubicTo(14.8152f, 18.435f, 15.1667f, 19.2826f, 15.1667f, 20.1667f)
                lineTo(15.1667f, 22.6667f)
                close()
                moveTo(26f, 22.6667f)
                cubicTo(26f, 23.5507f, 25.6486f, 24.3983f, 25.0234f, 25.0234f)
                cubicTo(24.3983f, 25.6486f, 23.5507f, 26f, 22.6667f, 26f)
                lineTo(20.1667f, 26f)
                cubicTo(19.2826f, 26f, 18.435f, 25.6486f, 17.8099f, 25.0234f)
                cubicTo(17.1848f, 24.3983f, 16.8333f, 23.5507f, 16.8333f, 22.6667f)
                lineTo(16.8333f, 20.1667f)
                cubicTo(16.8333f, 19.2826f, 17.1848f, 18.435f, 17.8099f, 17.8099f)
                cubicTo(18.435f, 17.1848f, 19.2826f, 16.8333f, 20.1667f, 16.8333f)
                lineTo(22.6667f, 16.8333f)
                cubicTo(23.5507f, 16.8333f, 24.3983f, 17.1848f, 25.0234f, 17.8099f)
                cubicTo(25.6486f, 18.435f, 26f, 19.2826f, 26f, 20.1667f)
                lineTo(26f, 22.6667f)
                close()
                moveTo(15.1667f, 11.8333f)
                cubicTo(15.1667f, 12.7174f, 14.8152f, 13.565f, 14.1901f, 14.1901f)
                cubicTo(13.565f, 14.8152f, 12.7174f, 15.1667f, 11.8333f, 15.1667f)
                lineTo(9.33333f, 15.1667f)
                cubicTo(8.44928f, 15.1667f, 7.60168f, 14.8152f, 6.97656f, 14.1901f)
                cubicTo(6.35144f, 13.565f, 6f, 12.7174f, 6f, 11.8333f)
                lineTo(6f, 9.33333f)
                cubicTo(6f, 8.44928f, 6.35144f, 7.60168f, 6.97656f, 6.97656f)
                cubicTo(7.60168f, 6.35144f, 8.44928f, 6f, 9.33333f, 6f)
                lineTo(11.8333f, 6f)
                cubicTo(12.7174f, 6f, 13.565f, 6.35144f, 14.1901f, 6.97656f)
                cubicTo(14.8152f, 7.60168f, 15.1667f, 8.44928f, 15.1667f, 9.33333f)
                lineTo(15.1667f, 11.8333f)
                close()
                moveTo(26f, 11.8333f)
                cubicTo(26f, 12.7174f, 25.6486f, 13.565f, 25.0234f, 14.1901f)
                cubicTo(24.3983f, 14.8152f, 23.5507f, 15.1667f, 22.6667f, 15.1667f)
                lineTo(20.1667f, 15.1667f)
                cubicTo(19.2826f, 15.1667f, 18.435f, 14.8152f, 17.8099f, 14.1901f)
                cubicTo(17.1848f, 13.565f, 16.8333f, 12.7174f, 16.8333f, 11.8333f)
                lineTo(16.8333f, 9.33333f)
                cubicTo(16.8333f, 8.44928f, 17.1848f, 7.60168f, 17.8099f, 6.97656f)
                cubicTo(18.435f, 6.35144f, 19.2826f, 6f, 20.1667f, 6f)
                lineTo(22.6667f, 6f)
                cubicTo(23.5507f, 6f, 24.3983f, 6.35144f, 25.0234f, 6.97656f)
                cubicTo(25.6486f, 7.60168f, 26f, 8.44928f, 26f, 9.33333f)
                lineTo(26f, 11.8333f)
                close()
            }
            drawPath(path = path0, color = Color(0xFFCACED4))
        }
        NookIconName.Icon32MapSelected -> {
            val path0 = Path().apply {
                fillType = PathFillType.EvenOdd

                moveTo(13.6962f, 6.21863f)
                cubicTo(13.2372f, 6.02869f, 12.7215f, 6.02869f, 12.2625f, 6.21863f)
                lineTo(7.1575f, 8.33113f)
                cubicTo(6.81485f, 8.47305f, 6.52198f, 8.71341f, 6.31594f, 9.02179f)
                cubicTo(6.10991f, 9.33018f, 5.99996f, 9.69274f, 6f, 10.0636f)
                lineTo(6f, 23.6599f)
                cubicTo(5.99997f, 23.9682f, 6.07598f, 24.2718f, 6.22132f, 24.5438f)
                cubicTo(6.36665f, 24.8158f, 6.57682f, 25.0477f, 6.8332f, 25.219f)
                cubicTo(7.08958f, 25.3904f, 7.38427f, 25.4958f, 7.69114f, 25.5261f)
                cubicTo(7.99801f, 25.5563f, 8.30761f, 25.5104f, 8.5925f, 25.3924f)
                lineTo(12.98f, 23.5761f)
                lineTo(18.305f, 25.7799f)
                cubicTo(18.7637f, 25.9695f, 19.2788f, 25.9695f, 19.7375f, 25.7799f)
                lineTo(24.8412f, 23.6674f)
                cubicTo(25.1841f, 23.5256f, 25.4773f, 23.2854f, 25.6835f, 22.977f)
                cubicTo(25.8898f, 22.6686f, 25.9999f, 22.3059f, 26f, 21.9349f)
                lineTo(26f, 8.34113f)
                cubicTo(26f, 8.03292f, 25.9239f, 7.72949f, 25.7787f, 7.45767f)
                cubicTo(25.6334f, 7.18585f, 25.4234f, 6.95403f, 25.1671f, 6.78273f)
                cubicTo(24.9109f, 6.61142f, 24.6164f, 6.50592f, 24.3097f, 6.47555f)
                cubicTo(24.003f, 6.44519f, 23.6936f, 6.49089f, 23.4088f, 6.60863f)
                lineTo(19.0212f, 8.42363f)
                lineTo(13.6962f, 6.21988f)
                lineTo(13.6962f, 6.21863f)
                close()
                moveTo(12.975f, 9.74988f)
                cubicTo(13.2236f, 9.74988f, 13.4621f, 9.84865f, 13.6379f, 10.0245f)
                cubicTo(13.8137f, 10.2003f, 13.9125f, 10.4387f, 13.9125f, 10.6874f)
                lineTo(13.9125f, 18.8124f)
                cubicTo(13.9125f, 19.061f, 13.8137f, 19.2995f, 13.6379f, 19.4753f)
                cubicTo(13.4621f, 19.6511f, 13.2236f, 19.7499f, 12.975f, 19.7499f)
                cubicTo(12.7264f, 19.7499f, 12.4879f, 19.6511f, 12.3121f, 19.4753f)
                cubicTo(12.1363f, 19.2995f, 12.0375f, 19.061f, 12.0375f, 18.8124f)
                lineTo(12.0375f, 10.6874f)
                cubicTo(12.0375f, 10.4387f, 12.1363f, 10.2003f, 12.3121f, 10.0245f)
                cubicTo(12.4879f, 9.84865f, 12.7264f, 9.74988f, 12.975f, 9.74988f)
                close()
                moveTo(19.9625f, 13.1874f)
                cubicTo(19.9625f, 12.9387f, 19.8637f, 12.7003f, 19.6879f, 12.5245f)
                cubicTo(19.5121f, 12.3486f, 19.2736f, 12.2499f, 19.025f, 12.2499f)
                cubicTo(18.7764f, 12.2499f, 18.5379f, 12.3486f, 18.3621f, 12.5245f)
                cubicTo(18.1863f, 12.7003f, 18.0875f, 12.9387f, 18.0875f, 13.1874f)
                lineTo(18.0875f, 21.3124f)
                cubicTo(18.0875f, 21.561f, 18.1863f, 21.7995f, 18.3621f, 21.9753f)
                cubicTo(18.5379f, 22.1511f, 18.7764f, 22.2499f, 19.025f, 22.2499f)
                cubicTo(19.2736f, 22.2499f, 19.5121f, 22.1511f, 19.6879f, 21.9753f)
                cubicTo(19.8637f, 21.7995f, 19.9625f, 21.561f, 19.9625f, 21.3124f)
                lineTo(19.9625f, 13.1874f)
                close()
            }
            drawPath(path = path0, color = Color(0xFF1F1F1F))
        }
        NookIconName.Icon32MapUnselected -> {
            val path0 = Path().apply {

                moveTo(0f, 0f)
                lineTo(32f, 0f)
                lineTo(32f, 32f)
                lineTo(0f, 32f)
                close()
            }
            drawPath(path = path0, color = Color(0xFFFFFFFF))
            val path1 = Path().apply {

                moveTo(24.4621f, 21.441f)
                lineTo(24.4621f, 8.63559f)
                cubicTo(24.462f, 8.35005f, 24.1607f, 8.16428f, 23.905f, 8.29213f)
                lineTo(19.9367f, 10.2745f)
                lineTo(19.9376f, 10.2754f)
                cubicTo(19.3958f, 10.547f, 18.7568f, 10.5471f, 18.2149f, 10.2745f)
                lineTo(13.0946f, 7.71519f)
                cubicTo(13.0414f, 7.68869f, 12.9827f, 7.67467f, 12.9233f, 7.67463f)
                cubicTo(12.8637f, 7.67463f, 12.8044f, 7.68857f, 12.7511f, 7.71519f)
                lineTo(7.75065f, 10.215f)
                cubicTo(7.62013f, 10.2803f, 7.53805f, 10.4136f, 7.53791f, 10.5584f)
                lineTo(7.53791f, 23.3647f)
                cubicTo(7.53816f, 23.6501f, 7.83939f, 23.836f, 8.09501f, 23.7082f)
                lineTo(12.0633f, 21.724f)
                cubicTo(12.6043f, 21.4531f, 13.2421f, 21.4523f, 13.7833f, 21.724f)
                lineTo(18.9036f, 24.2851f)
                cubicTo(19.0105f, 24.3384f, 19.1351f, 24.3378f, 19.2408f, 24.2878f)
                cubicTo(19.2434f, 24.2865f, 19.2463f, 24.2855f, 19.2489f, 24.2842f)
                lineTo(24.2493f, 21.7853f)
                cubicTo(24.3787f, 21.7208f, 24.4621f, 21.5867f, 24.4621f, 21.441f)
                close()
                moveTo(18.3078f, 21.3851f)
                lineTo(18.3078f, 12.923f)
                cubicTo(18.3078f, 12.4982f, 18.652f, 12.1542f, 19.0767f, 12.154f)
                cubicTo(19.5016f, 12.154f, 19.8466f, 12.4981f, 19.8466f, 12.923f)
                lineTo(19.8466f, 21.3851f)
                cubicTo(19.8464f, 21.8098f, 19.5015f, 22.154f, 19.0767f, 22.154f)
                cubicTo(18.6521f, 22.1539f, 18.3079f, 21.8097f, 18.3078f, 21.3851f)
                close()
                moveTo(12.1534f, 19.0773f)
                lineTo(12.1534f, 10.6152f)
                cubicTo(12.1534f, 10.1904f, 12.4984f, 9.84627f, 12.9233f, 9.84627f)
                cubicTo(13.348f, 9.84643f, 13.6922f, 10.1905f, 13.6922f, 10.6152f)
                lineTo(13.6922f, 19.0773f)
                cubicTo(13.6921f, 19.5019f, 13.3479f, 19.8461f, 12.9233f, 19.8463f)
                cubicTo(12.4985f, 19.8463f, 12.1536f, 19.502f, 12.1534f, 19.0773f)
                close()
                moveTo(26f, 21.441f)
                cubicTo(26f, 22.1691f, 25.5885f, 22.8366f, 24.9363f, 23.1619f)
                lineTo(19.9466f, 25.6553f)
                cubicTo(19.9432f, 25.6571f, 19.9402f, 25.6599f, 19.9367f, 25.6616f)
                cubicTo(19.3957f, 25.9321f, 18.7584f, 25.9312f, 18.2176f, 25.6616f)
                lineTo(13.0928f, 23.0997f)
                cubicTo(12.9866f, 23.0464f, 12.8603f, 23.0454f, 12.752f, 23.0997f)
                lineTo(12.7511f, 23.1006f)
                lineTo(8.78284f, 25.0838f)
                cubicTo(7.50428f, 25.7231f, 6.00026f, 24.7938f, 6f, 23.3647f)
                lineTo(6f, 10.5584f)
                cubicTo(6.00015f, 9.83186f, 6.41022f, 9.16573f, 7.06283f, 8.83932f)
                lineTo(12.0633f, 6.33955f)
                cubicTo(12.3303f, 6.20611f, 12.6248f, 6.13672f, 12.9233f, 6.13672f)
                cubicTo(13.2217f, 6.13677f, 13.5164f, 6.20614f, 13.7833f, 6.33955f)
                lineTo(13.7824f, 6.34045f)
                lineTo(18.9072f, 8.90062f)
                cubicTo(19.0134f, 8.95388f, 19.1397f, 8.95404f, 19.248f, 8.89972f)
                lineTo(23.2172f, 6.91559f)
                cubicTo(24.4958f, 6.27631f, 25.9999f, 7.20633f, 26f, 8.63559f)
                lineTo(26f, 21.441f)
                close()
            }
            drawPath(path = path1, color = Color(0xFFCACED4))
        }
        NookIconName.Icon32StarOff -> {
            drawCircle(color = Color(0xFFF4F5F7), center = Offset(16f, 16f), radius = 16f)
            val path1 = Path().apply {
                fillType = PathFillType.EvenOdd

                moveTo(20.6433f, 9.49927f)
                lineTo(22.5f, 9.49927f)
                lineTo(22.5f, 22.4993f)
                lineTo(20.6433f, 22.4993f)
                lineTo(20.6433f, 24.356f)
                lineTo(18.7856f, 24.356f)
                lineTo(18.7856f, 22.4993f)
                lineTo(16.9289f, 22.4993f)
                lineTo(16.9289f, 20.6426f)
                lineTo(15.0711f, 20.6426f)
                lineTo(15.0711f, 22.4993f)
                lineTo(13.2144f, 22.4993f)
                lineTo(13.2144f, 24.356f)
                lineTo(11.3567f, 24.356f)
                lineTo(11.3567f, 22.4993f)
                lineTo(9.5f, 22.4993f)
                lineTo(9.5f, 9.49927f)
                lineTo(11.3567f, 9.49927f)
                lineTo(11.3567f, 7.64258f)
                lineTo(20.6433f, 7.64258f)
                lineTo(20.6433f, 9.49927f)
                close()
                moveTo(15.0711f, 13.2137f)
                lineTo(16.9289f, 13.2137f)
                lineTo(16.9289f, 11.356f)
                lineTo(15.0711f, 11.356f)
                lineTo(15.0711f, 13.2137f)
                close()
            }
            drawPath(path = path1, color = Color(0xFFB5BBC3))
        }
        NookIconName.Icon32StarOn -> {
            drawCircle(color = Color(0xFFF4F5F7), center = Offset(16f, 16f), radius = 16f)
            val path1 = Path().apply {
                fillType = PathFillType.EvenOdd

                moveTo(20.6433f, 9.49927f)
                lineTo(22.5f, 9.49927f)
                lineTo(22.5f, 22.4993f)
                lineTo(20.6433f, 22.4993f)
                lineTo(20.6433f, 24.356f)
                lineTo(18.7856f, 24.356f)
                lineTo(18.7856f, 22.4993f)
                lineTo(16.9289f, 22.4993f)
                lineTo(16.9289f, 20.6426f)
                lineTo(15.0711f, 20.6426f)
                lineTo(15.0711f, 22.4993f)
                lineTo(13.2144f, 22.4993f)
                lineTo(13.2144f, 24.356f)
                lineTo(11.3567f, 24.356f)
                lineTo(11.3567f, 22.4993f)
                lineTo(9.5f, 22.4993f)
                lineTo(9.5f, 9.49927f)
                lineTo(11.3567f, 9.49927f)
                lineTo(11.3567f, 7.64258f)
                lineTo(20.6433f, 7.64258f)
                lineTo(20.6433f, 9.49927f)
                close()
                moveTo(15.0711f, 13.2137f)
                lineTo(16.9289f, 13.2137f)
                lineTo(16.9289f, 11.356f)
                lineTo(15.0711f, 11.356f)
                lineTo(15.0711f, 13.2137f)
                close()
            }
            drawPath(path = path1, color = Color(0xFF558EFF))
        }
        NookIconName.Icon40Location -> {
            drawCircle(color = Color(0xFFFFFFFF), center = Offset(20f, 20f), radius = 20f)
            drawCircle(color = Color(0xFF1F1F1F), center = Offset(20f, 20f), radius = 8f, style = Stroke(width = 1f, cap = StrokeCap.Butt))
            val path2 = Path().apply {

                moveTo(12f, 20f)
                lineTo(15f, 20f)
            }
            drawPath(path = path2, color = Color(0xFF1F1F1F), style = Stroke(width = 1f, cap = StrokeCap.Round))
            val path3 = Path().apply {

                moveTo(25f, 20f)
                lineTo(28f, 20f)
            }
            drawPath(path = path3, color = Color(0xFF1F1F1F), style = Stroke(width = 1f, cap = StrokeCap.Round))
            val path4 = Path().apply {

                moveTo(20f, 12f)
                lineTo(20f, 15f)
            }
            drawPath(path = path4, color = Color(0xFF1F1F1F), style = Stroke(width = 1f, cap = StrokeCap.Round))
            val path5 = Path().apply {

                moveTo(20f, 25f)
                lineTo(20f, 28f)
            }
            drawPath(path = path5, color = Color(0xFF1F1F1F), style = Stroke(width = 1f, cap = StrokeCap.Round))
        }
        NookIconName.CheckBtnSelected -> {
            drawCircle(color = Color(0xFF1F1F1F), center = Offset(12f, 12f), radius = 11f)
            val path1 = Path().apply {

                moveTo(7f, 11.8942f)
                lineTo(10.4042f, 15.2979f)
                lineTo(17f, 8.70215f)
            }
            drawPath(path = path1, color = Color(0xFFFFFFFF), style = Stroke(width = 1.5f, cap = StrokeCap.Butt))
        }
        NookIconName.CheckBtnUnselected -> {
            drawCircle(color = Color(0xFFE4E6E9), center = Offset(12f, 12f), radius = 11f)
            val path1 = Path().apply {

                moveTo(7f, 11.8942f)
                lineTo(10.4042f, 15.2979f)
                lineTo(17f, 8.70215f)
            }
            drawPath(path = path1, color = Color(0xFFFFFFFF), style = Stroke(width = 1.5f, cap = StrokeCap.Butt))
        }
        NookIconName.LocationCrosshair -> {
            drawCircle(color = Color(0xFF1F1F1F), center = Offset(8.5f, 8.5f), radius = 8f, style = Stroke(width = 1f, cap = StrokeCap.Butt))
            val path1 = Path().apply {

                moveTo(0.5f, 8.5f)
                lineTo(3.5f, 8.5f)
            }
            drawPath(path = path1, color = Color(0xFF1F1F1F), style = Stroke(width = 1f, cap = StrokeCap.Round))
            val path2 = Path().apply {

                moveTo(13.5f, 8.5f)
                lineTo(16.5f, 8.5f)
            }
            drawPath(path = path2, color = Color(0xFF1F1F1F), style = Stroke(width = 1f, cap = StrokeCap.Round))
            val path3 = Path().apply {

                moveTo(8.5f, 0.5f)
                lineTo(8.5f, 3.5f)
            }
            drawPath(path = path3, color = Color(0xFF1F1F1F), style = Stroke(width = 1f, cap = StrokeCap.Round))
            val path4 = Path().apply {

                moveTo(8.5f, 13.5f)
                lineTo(8.5f, 16.5f)
            }
            drawPath(path = path4, color = Color(0xFF1F1F1F), style = Stroke(width = 1f, cap = StrokeCap.Round))
        }
        }
        drawContext.canvas.restore()
    }
}
